"""Initial Migration

Revision ID: 4447ccaae5b8
Revises: fc69bb1d1240
Create Date: 2021-03-12 12:43:56.905450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4447ccaae5b8'
down_revision = 'fc69bb1d1240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leases', 'profile_pic_path')
    # ### end Alembic commands ###
